[package]
name = "elifrs"
version = "0.1.0"
edition = "2021"
description = "LLM-friendly Rust web framework CLI - AI agent-optimized development tools"
license = "MIT"
authors = ["krcpa <krcpa@users.noreply.github.com>"]
repository = "https://github.com/krcpa/elif.rs"
homepage = "https://github.com/krcpa/elif.rs"
documentation = "https://docs.rs/elifrs"
readme = "README.md"
keywords = ["web", "framework", "cli", "ai", "llm"]
categories = ["command-line-utilities", "web-programming", "development-tools"]

[[bin]]
name = "elif"
path = "src/main.rs"

[dependencies]
elif-core = { version = "0.1.0", path = "../core" }
elif-codegen = { version = "0.1.0", path = "../codegen" }
elif-introspect = { version = "0.1.0", path = "../introspect" }
clap = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }