[package]
name = "elif-orm"
version = "0.1.0"
edition = "2021"

[dependencies]
elif-core = { path = "../core" }
sqlx = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }