[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Prevent Axum types in test files to maintain framework abstraction
[env]
RUSTFLAGS = "--deny warnings --warn clippy::disallowed_types"

# Custom lint configuration
[build]
rustflags = [
    "-D", "warnings",
    "-W", "clippy::disallowed_types",
]